# Generated by Django 5.0.6 on 2024-06-17 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socual_management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.IntegerField(choices=[(0, 'Admin'), (1, 'Organisation')], default=1),
        ),
        migrations.AlterModelTable(
            name='user',
            table='users',
        ),
    ]
