# Generated by Django 5.0.6 on 2024-06-17 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socual_management', '0003_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
